travis:
  secure:
    BINSTAR_TOKEN: JL3dR0HSQ800RS/mcBns202K260Tu0AX7c8esw8LKWUQPRQ5u6khtLq5kHVgHo2nKUWCqWTsgc+FPQbrF+ymYcXCi3eqBbNqsT7XVPuZafcv+yU6ZvrZB3NWIXi3c9XEVgpQrwrIWLIIRhbcREmzJn9ACOsphV33NoOTZB8YU0DGG2N4EjolNDmWnv/fmaDUFaWbQK4AIEJjGLunup0QAaqIMFc8qtJWpAJb9NNt4YFsJyKXC4BBX/8cKrlp4/kxMjlQaW0/3wAF9DrXAR4OUrzrzgrTG6cXBXI0J1P3EJkbOFiDX8C+NCnbcnJTJ8gvXFFKcbUNhxGqnAhzrR/GyaOJwyHrtCkF7I+w74Qr/6lO6ddtSI/HJ29GoPpLCNbcIyF2Ec3wN3sKP2fNI9lZBljy+RMhLy/Vmo6eIdaZKO0fB+AySzqJZ8EebKGvMCBc3sU42Wqzl0aG0Eq99Mq63iEJQRjt+w6OL8/tgo3lFQQT2hy/VsKi1y5Eo0WbSGQXZWGfuDj31IVkCTZ1JFw8vG2D4kbQyxmvLAXR8A+5UUIoLibEFJwhSSl93l4yuozUGhTzKvSunQSCysz4fqh49r/dJV7jJpxamaxcYgGLJKOs1/yZ5S1k8Hx/n/v6a9WCtnYkx3cgyi/mQPqgvj1NFJYPrNSrM7hlxMLT54hSiNk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
