appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: TNXPnIUmp0JguhwQ9ODUiYWSovomOeQabU+j+RQDayG9M1fhz44Hq6AAEPEi/dt46sOqR4VjlBHXNQmeBbhxm6yVPZawUzaF/DdP2JSyGMInKSQ9lsqhSiqG73B6dH6SNYNoIefpnG4E9PiZTN+sgFVWoydNMrSBuJ6tSeKZnuuOgz/mm6Z4rvZozbkUbpuJcJ375Sx6Vb26H/vqLRtycgUr/cZpn+g66e9nZ8fwWSAKkyKZsd/BZLBFwt6+yJ3kZitY2gTNRZSqIYl+iOMiyVh8EcY8kA8PfxpQdT8mDS25DS+9fnLqZL1tWr0demR4VGBZQCqGReUFfoWJ1uf1qXLN45LsgWp15+zUdfFVDfxWdU5TqVvgNYskjvBmRt8TLcmSooYfeCaovF8KLi5pkD3/5gQTUOR3jbqV3eXwihSV9/0YQhKx5/i2Cbt3mHNpWSeyAfd3Gnu4DABSZ7D72DIO7XuSrUmau8vcg6aQdDDAYqtD3J8EsRfUQHFmEYR5/QkO9srLQPPAlzlvvt6uvAlwlDCdbpgf9sVVoNDYvtCrvQBPcnr93nC4gPKa+gherw6Ujzdd4d00N2QDUucxdC3/OXB2lkv24dAICiPgx2gvT3Q8A2Q0URWeCn9FFnOFFikECiuGmcE3iMAtvZ96MGsUXOjfxmMPqMz2lJyCkyE=
conda_forge_output_validation: true
