travis:
  secure:
    BINSTAR_TOKEN: xuEx8L98pXkEOkG1a1jZ97cDndQSwRDwLtYmBw35mbHJNqSc/G56Ty22EjHknLq8zkWFXaapAxvXFbzG0rvzJ71fCpEjj+Q2/z70qZ0OlW0wqbrBWyAvKNc8Svwvwahyq8eRzAvEo7jUzi3PAST4ReBS8QJbJ9H3bOm0mAFmlDZBWqnBg4fM9Gup8NS6EJF9mY/IjKZPZ+woVQ+ErNdkkr2mocWzGbPyO5+qEGSH6qjbSuea8qlYgrWk31pqCSjQ92aUUoiPDf7kwyFnkYFKWqHMpK5uH94JnN9M4ja0bLoP0Oq/aHeMMj+m6KM75wAUGjPAI06SV9IuOOatHyAVBzIR2eNw+Qcr6YYyPZsIePi5pppVHEbc/FCt/XE+6jDdHIOwQ3sX/nLKhBR8YmlM5UUAsBH9OBRN+FaxvLNPI/ta+qJ4yiOR2bc/7W1KmC1hFabCdpwp7BtcK70EmGSE86yWq9qZh4nERaKMJ7gZhd8qOyjxCHsD6Y+Yu31RroaI2w6n+/RTfkR4O/XjgwpodoYtHnct7wb2TQhq35JmRwvtut+GkbzyBRWstJ+UNDwTVYf5eJVJ/gPBteJWMR6MQ5FgjafvCskIPy2+0p1b1DAdWOYJHw1O/SpC27hMt/mRPzolPeAx64U8P2VNVTgkWEtx2QcXchBsTxAanzCIz1Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
